### 登录 ok
POST http://localhost:1001/api/v1/user/login HTTP/1.1
Content-Type: application/json

{
    "userId": "useruser1",
    "password": "123456"
}

### 注册 ok
POST http://localhost:1001/api/v1/user/register HTTP/1.1
content-type: application/json

{
    "nickName": "用户4",
    "userRole": 1,
    "gender": 1,
    "userId": "useruser4",
    "password": "123456"
}

### 查单条 ok
GET http://localhost:1001/api/v1/user/useruser1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ0ZXN0dGVzdDEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2MzY2MzM3NCwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzU3Njg3NH0.YEd0XsFZdvsHsgicvNz5Pf9l-JmD1OJI9KaMTdSO5pw

### 修改个人信息 ok
PUT http://localhost:1001/api/v1/user/ac0de809143a45a6bf5df8a55579ebcd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ0ZXN0dGVzdDEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2MzY2MzM3NCwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzU3Njg3NH0.YEd0XsFZdvsHsgicvNz5Pf9l-JmD1OJI9KaMTdSO5pw
content-type: application/json

{
    "nickName": "用户1",
    "userRole": 1,
    "gender": 1,
    "userId": "testtest12345",
    "password": "12345678"
}

### 注销 ok
DELETE http://localhost:1001/api/v1/user/077309ea4f3f4bc9a7c8dc9c71bc65d7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ0ZXN0dGVzdDEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2MzY2MzM3NCwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzU3Njg3NH0.YEd0XsFZdvsHsgicvNz5Pf9l-JmD1OJI9KaMTdSO5pw

### 发送验证信息 ok
POST http://localhost:1001/api/v1/relation/validate HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VydXNlcjIiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2Mzc0OTgzMCwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzY2MzMzMH0.26wKc8jkTTtAi7VCz4w9EXxc9rfEO-38Udd2vu7G018

{
    "userId": "useruser1",
    "friendId": "useruser3",
    "memo": "我是user1，想添加user3为好友。"
}

### 查询验证列表 ok
GET http://localhost:1001/api/v1/relation/list/validate/useruser2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VydXNlcjIiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2Mzc0OTgzMCwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzY2MzMzMH0.26wKc8jkTTtAi7VCz4w9EXxc9rfEO-38Udd2vu7G018

### 查询好友列表 ok
GET http://localhost:1001/api/v1/relation/list/friend/useruser1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VydXNlcjEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2Mzc1NjM2NiwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzY2OTg2Nn0.O999U-eLUqvOR1ZjkhM41kv02WhTa8zEV5bO1Em6vOk

### 添加好友 ok
POST http://localhost:1001/api/v1/relation/friend HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VydXNlcjIiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2Mzc0OTgzMCwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzY2MzMzMH0.26wKc8jkTTtAi7VCz4w9EXxc9rfEO-38Udd2vu7G018

{
    "userId": "useruser3",
    "friendId": "useruser1"
}

### 删除好友 ok
DELETE http://localhost:1001/api/v1/relation/friend HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VydXNlcjEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImV4cCI6MTY2Mzc1NjM2NiwiaXNzIjoicXVpY2stY2hhdCIsIm5iZiI6MTY2MzY2OTg2Nn0.O999U-eLUqvOR1ZjkhM41kv02WhTa8zEV5bO1Em6vOk

{
    "userId": "useruser2",
    "friendId": "useruser1"
}